# Generated by Django 4.0.5 on 2022-06-13 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('birth_date', models.DateField(null=True)),
                ('profile_photo', models.ImageField(default='profiles/logo2.png', max_length=255, null=True, upload_to='profiles')),
                ('avatar_url', models.CharField(blank=True, max_length=256, null=True)),
                ('social_google', models.CharField(blank=True, max_length=250, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
