# Generated by Django 4.0.5 on 2022-06-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='profiles/logo2.png', max_length=255, null=True, upload_to='profiles'),
        ),
    ]
